/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises_week3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // CONDITIONAL EXERCISES*********

        // 1. Write a program that prompts the user to enter
        // an integer and checks whether it is positive.

        // Scanner input = new Scanner(System.in);
        // System.out.println("Please enter an integer");
        // int userInt = input.nextInt();
        // if (userInt < 0){
        // System.out.println("That's a negative integer");
        // }else{
        // System.out.println("That's a positive integer");
        // }
        // input.close();

        // 2. Write a program that prompts the user to enter two
        // integers and checks whether they are equal.
        // Scanner input = new Scanner(System.in);
        // System.out.println("Please enter your first integer");
        // int firstUserInt = input.nextInt();
        // System.out.println("Please enter your second integer");
        // int secondUserInt = input.nextInt();
        // if(firstUserInt == secondUserInt){
        // System.out.println("The two integers entered are equal");
        // }else{
        // System.out.println("The two integers entered are not equal");
        // }
        // input.close();

        // 3. Write a program that prompts the user to enter
        // a character and checks whether it is a vowel.
        // Scanner input = new Scanner(System.in);
        // System.out.println("Please enter a character (for example a, b, or c):");
        // char userCharEntered = input.next().charAt(0);
        // if (userCharEntered == 'a' || userCharEntered == 'e' || userCharEntered ==
        // 'i' || userCharEntered == 'o' || userCharEntered == 'u' || userCharEntered ==
        // 'y'){
        // System.out.println("This character is a vowel");
        // }else{
        // System.out.println("This character is not a vowel");
        // }
        // input.close();
        // 4.

        // FOR LOOP EXERCISES**********

        // 1. Write a program that prints the sum of the
        // numbers from 1 to 100 using a for loop
        // int sum = 0;
        // for(int i = 1; i<=100; i++){
        // sum = sum + i;}
        // System.out.println(sum);

        // 2. Write a program that prints the even numbers from 1 to 20 using a for
        // loop.
        // for (int i = 2; i <= 20; i += 2) {
        // System.out.println(i);
        // }

        // 3. Write a program that prints the odd numbers from 1 to 15 using a for loop.
        // for(int i=1;i<=15;i+=2){
        // System.out.println(i);
        // }

        // WHILE LOOP EXERCISES *******
        // 1. Write a program that prompts the user to enter a number and prints the
        // sum of all numbers from 1 to that number using a while loop.
        // Scanner input = new Scanner(System.in);
        // System.out.println("Please enter a number");
        // int userNumber = input.nextInt();
        // int sum = 0;
        // int i = 1;
        // while(i <= userNumber){
        // sum += i;
        // i++;
        // }
        // System.out.println("The sum of all numbers from 1 to " + userNumber + " is: "
        // + sum);
        // input.close();

        // 2. Write a program that prints all the numbers
        // from 100 to 1 using a while loop.
        // int number = 101;
        // while(number >= 1){
        // number--;
        // System.out.println(number);
        // }
        // 3. Write a program that prompts the user to enter a number
        // and prints the factorial of that number using a while loop
        // Scanner input = new Scanner(System.in);
        // System.out.println("Please enter a number");
        // int userIntiger = input.nextInt();
        // int i = 1;
        // int sum = 1;
        // while(i < userIntiger){
        // sum *= i;
        // i++;
        // }
        // System.out.println("The factorial of " + userIntiger + " is: " + sum);

    }
}